Add MODULES env var and rename module folders

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -9,7 +9,7 @@ SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 source "$SCRIPT_DIR"/common
 
 setup_gitconfig () {
-    if ! [[ -f "$SCRIPT_DIR"/001_git/.gitconfig ]]; then
+    if ! [[ -f "$SCRIPT_DIR"/git/.gitconfig ]]; then
         info 'setup gitconfig'
 
         git_credential='cache'
@@ -25,7 +25,7 @@ setup_gitconfig () {
         sed -e "s/AUTHORNAME/$git_authorname/g" \
             -e "s/AUTHOREMAIL/$git_authoremail/g" \
             -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" \
-            "$SCRIPT_DIR"/001_git/.gitconfig.example > "$SCRIPT_DIR"/001_git/.gitconfig
+            "$SCRIPT_DIR"/git/.gitconfig.example > "$SCRIPT_DIR"/git/.gitconfig
 
         success 'gitconfig'
     fi
@@ -36,16 +36,17 @@ install_symlinks () {
 
     overwrite_all=false backup_all=false skip_all=false
 
-    symlink_files=()
-    while IFS=" " read -r line; do symlink_files+=("$line"); done < <(find -H "$SCRIPT_DIR" -maxdepth 2 -name 'symlink.sh' | sort)
-
-    for symlink_file in "${symlink_files[@]}"; do
+    for module in "${MODULES[@]}"; do
+        if [[ ! -f "$module/symlink.sh" ]]; then
+            warn "no symlink.sh file found for $module, skipping"
+            continue
+        fi
         info ""
-        info "running symlink file $symlink_file"
+        info "running symlink file : $module/symlink.sh"
         info "==========================================="
         info ""
-        if ! symlinks=$(sh -c "$symlink_file" 2>&1); then
-            fail "failed to run symlink file $symlink_file"
+        if ! symlinks=$(sh -c "$module/symlink.sh" 2>&1); then
+            fail "failed to run symlink file : $module/symlink.sh"
         else
             for link in "${symlinks[@]}"; do
                 lines=()
@@ -56,7 +57,7 @@ install_symlinks () {
                 done
             done
             info ""
-            success "finished symlink file $symlink_file"
+            success "finished symlink file : $module/symlink.sh"
             info "==========================================="
         fi
     done
diff --git a/install b/install
--- a/install
+++ b/install
@@ -8,38 +8,26 @@ SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 
 source "$SCRIPT_DIR"/common
 
-# find all installers and run them iteratively
-installers=()
-while IFS=" " read -r line; do installers+=("$line"); done < <(find . -name install.sh | sort)
-
 echo ""
 
+# find all installers and run them iteratively
 info "running installers : log file -> $LOG_FILE"
-for installer in "${installers[@]}"; do
+for module in "${MODULES[@]}"; do
     info ""
     info "==========================================="
 
-    skip_installer=0
-    for skip in "${SKIP_INSTALLERS[@]}"; do
-        if echo "$installer" | grep "_$skip/" > /dev/null; then
-            skip_installer=1
-            break
-        fi
-    done
-
-    if [[ $skip_installer -eq 1 ]]; then
-        warn "skipping installer $installer"
-        info "==========================================="
+    if [[ ! -d "./$module" ]]; then
+        warn "installer not found : $module" 
         continue
-    else
-        info "running installer $installer"
-        info ""
     fi
 
-    if ! sh -c "$installer"; then
-        fail "failed to run installer $installer"
+    info "running installer : $module/install.sh"
+    info ""
+
+    if ! sh -c "$module/install.sh"; then
+        fail "failed to run installer : $module/install.sh"
     else
-        success "finished installer $installer"
+        success "finished installer : $module/install.sh"
     fi
 
     info "==========================================="
