Clean up how we log installer output to debug.log

diff --git a/install b/install
--- a/install
+++ b/install
@@ -14,7 +14,7 @@ while IFS=" " read -r line; do installers+=("$line"); done < <(find . -name inst
 
 echo ""
 
-info "running installers : log file -> $LOG_FILE" | tee -a "$LOG_FILE"
+info "running installers : log file -> $LOG_FILE"
 for installer in "${installers[@]}"; do
     info ""
     info "==========================================="
@@ -28,18 +28,18 @@ for installer in "${installers[@]}"; do
     done
 
     if [[ $skip_installer -eq 1 ]]; then
-        warn "skipping installer $installer" | tee -a "$LOG_FILE"
+        warn "skipping installer $installer"
         info "==========================================="
         continue
     else
-        info "running installer $installer" | tee -a "$LOG_FILE"
+        info "running installer $installer"
         info ""
     fi
 
-    if ! sh -c "$installer" | tee -a "$LOG_FILE" 2>&1; then
-        fail "failed to run installer $installer" | tee -a "$LOG_FILE"
+    if ! sh -c "$installer"; then
+        fail "failed to run installer $installer"
     else
-        success "finished installer $installer" | tee -a "$LOG_FILE"
+        success "finished installer $installer"
     fi
 
     info "==========================================="
