Fix all custom scripts in bin/

diff --git a/001_zsh/bin/git-pr-create b/001_zsh/bin/git-pr-create
--- a/001_zsh/bin/git-pr-create
+++ b/001_zsh/bin/git-pr-create
@@ -10,10 +10,11 @@ pr_title=
 while [[ $# -gt 0 ]]; do
     case $1 in
     -l|--label)
+        # shellcheck disable=SC2076
         if [[ " ${pr_types[*]} " =~ " ${2} " ]]; then
             pr_type=$2
         fi
-        args+=($1 $2)
+        args+=("$1" "$2")
         shift; shift
         ;;
     -t|--title)
@@ -24,26 +25,26 @@ while [[ $# -gt 0 ]]; do
 done
 
 if [[ -z $pr_type ]]; then
-    >&2 echo "\nERROR: you need to provide a PR type as a label in (${pr_types[@]})"
-    return 1
+    >&2 printf "\nERROR: you need to provide a PR type in a -l|--label flag, examples (%s)\n" "${pr_types[*]}"
+    exit 1
 fi
 
 if [[ -z $pr_title ]]; then
     pr_title=$(git log -1 --pretty=%B)
-    >&2 echo "\nNo PR title provided, defaulting to last commit message \"$pr_title\""
+    >&2 printf "\nNo PR title provided, defaulting to last commit message \"%s\"\n" "$pr_title"
 else
-    >&2 echo "\nUsing \"$pr_title\" as PR title"
+    >&2 printf "\nUsing \"%s\" as PR title\n" "$pr_title"
 fi
 
 gh pr create \
     --head "$(git branch --show-current)" \
     --assignee "@me" \
     --title "$pr_title" \
-    "$args" || return $?
+    "${args[@]}" || return $?
 
-local url=$(gh pr view --json url --jq .url)
+url=$(gh pr view --json url --jq .url)
 
->&2 echo "\nThe below has been copied to your clipboard! 📋\n"
+>&2 printf "\nThe below has been copied to your clipboard! 📋\n\n"
 output=$(printf "%s\n:point_up: :%s: %s\n" "$url" "$pr_type" "$pr_title")
 echo "$output"
 echo "$output" | pbcopy
diff --git a/001_zsh/bin/gitw-add b/001_zsh/bin/gitw-add
--- a/001_zsh/bin/gitw-add
+++ b/001_zsh/bin/gitw-add
@@ -1,11 +1,51 @@
 #!/bin/bash
 
-set -e
+set -e 
 
-branch_name="$1"
-trimmed_name=$(echo "$branch_name" | cut  -d'/' -f2-)
+branch_name="$1"; shift
+
+if [[ -z $branch_name ]]; then
+    >&2 echo "ERROR: must provide a branch name"
+    exit 1
+fi
+
+# Remove the first path segment if branch name contains forward slashes
+trimmed_name=$(echo "$branch_name" | cut -d'/' -f2-)
+
+# Convert all forward slashes to dashes
 converted_name=${trimmed_name//\//-}
-git w add "$converted_name"
+
+# Create a new worktree using the converted name
+git worktree add "$converted_name" "$@"
+
+# Enter the new worktree
 cd "$converted_name" || exit
-git branch -m "$branch_name" || git checkout "$branch_name"
+
+# Attempt to rename worktree branch to use the correct branch name
+if ! output=$(git branch -m "$branch_name" 2>&1); then
+    # If the branch name already exists, check it out instead of creating it
+    if [[ $output == *"already exists"* ]]; then
+        >&2 echo "Branch '$branch_name' already exists"
+        git checkout "$branch_name"
+    fi
+fi
+
+# Post checkout setup
+if [[ -f "poetry.lock" ]]; then
+    >&2 echo
+    >&2 echo "========================"
+    >&2 echo "Running poetry install"
+    >&2 echo "========================"
+    >&2 echo
+    poetry install
+fi
+
+if [[ -f "pyproject.toml" ]] && [[ -f "$HOME/pyrightconfig.json" ]]; then
+    >&2 echo
+    >&2 echo "==============================="
+    >&2 echo "Linking pyrightconfig.json file"
+    >&2 echo "==============================="
+    >&2 echo
+    ln -s "$HOME/pyrightconfig.json" "pyrightconfig.json"
+fi
 
