Use existing PR files in git-pr-edit script

diff --git a/001_zsh/bin/git-pr-edit b/001_zsh/bin/git-pr-edit
--- a/001_zsh/bin/git-pr-edit
+++ b/001_zsh/bin/git-pr-edit
@@ -31,54 +31,76 @@ while [[ $# -gt 0 ]]; do
     esac
 done
 
-repo_labels=()
-while IFS=$'\n' read -r label; do repo_labels+=("$label"); done < <(gh label list --json name --jq '.[].name' --limit 100)
+# If a PR file already exists (if a previous attempt to create a PR has failed) use that file instead
+existing_old_pr_files=()
+while IFS=$'\n' read -r file; do existing_old_pr_files+=("$file"); done < <(find ./git-pr-edit*old* | sort --reverse)
 
-cur_time=$(date +%s)
-old_pr_file_name=git-pr-edit."$cur_time".old.md
-new_pr_file_name=git-pr-edit."$cur_time".new.md
+existing_new_pr_files=()
+while IFS=$'\n' read -r file; do existing_new_pr_files+=("$file"); done < <(find ./git-pr-edit*new* | sort --reverse)
 
-content=$(gh pr view --json title --json body --json labels)
-title=$(echo "$content" | jq -r .title)
-body=$(echo "$content" | jq -r .body)
+if [[ "${#existing_new_pr_files[@]}" -gt 0 ]]; then
+    old_pr_file_name="${existing_old_pr_files[0]}"
+    new_pr_file_name="${existing_new_pr_files[0]}"
+    info "Using existing PR file: $new_pr_file_name"
+    sleep 1
 
-labels=()
-while IFS=$'\n' read -r label; do labels+=("$label"); done < <(echo "$content" | jq -r .labels[].name)
+    if [[ $OSTYPE == "darwin"* ]]; then
+        old_file_md5=$(md5 -q "$old_pr_file_name")
+    else
+        old_file_md5=$(md5sum "$old_pr_file_name" | cut -d' ' -f1)
+    fi
 
-echo -e "--- TITLE\n$title\n--- END\n" > "$old_pr_file_name"
-echo -e "--- TITLE\n$title\n--- END\n" > "$new_pr_file_name"
-echo -e "--- EXISTING LABELS" >> "$old_pr_file_name"
-echo -e "--- EXISTING LABELS" >> "$new_pr_file_name"
-for label in "${repo_labels[@]}"; do
-    echo "$label" >> "$old_pr_file_name"
-    echo "$label" >> "$new_pr_file_name"
-done
-echo -e "--- END\n" >> "$old_pr_file_name"
-echo -e "--- END\n" >> "$new_pr_file_name"
-
-echo -e "--- LABELS" >> "$old_pr_file_name"
-echo -e "--- LABELS" >> "$new_pr_file_name"
-for label in "${labels[@]}"; do
-    echo "$label" >> "$old_pr_file_name"
-    echo "$label" >> "$new_pr_file_name"
-done
-echo -e "--- END\n" >> "$old_pr_file_name"
-echo -e "--- END\n" >> "$new_pr_file_name"
-
-echo -e "--- BODY\n" >> "$old_pr_file_name"
-echo -e "--- BODY\n" >> "$new_pr_file_name"
-echo "$body" >> "$old_pr_file_name"
-echo "$body" >> "$new_pr_file_name"
-echo -e "--- END\n" >> "$old_pr_file_name"
-echo -e "--- END\n" >> "$new_pr_file_name"
-
-if [[ $OSTYPE == "darwin"* ]]; then
-    old_file_md5=$(md5 -q "$old_pr_file_name")
+    $EDITOR "$new_pr_file_name"
 else
-    old_file_md5=$(md5sum "$old_pr_file_name" | cut -d' ' -f1)
-fi
+    repo_labels=()
+    while IFS=$'\n' read -r label; do repo_labels+=("$label"); done < <(gh label list --json name --jq '.[].name' --limit 100)
 
-$EDITOR "$new_pr_file_name"
+    cur_time=$(date +%s)
+    old_pr_file_name=git-pr-edit."$cur_time".old.md
+    new_pr_file_name=git-pr-edit."$cur_time".new.md
+
+    content=$(gh pr view --json title --json body --json labels)
+    title=$(echo "$content" | jq -r .title)
+    body=$(echo "$content" | jq -r .body)
+
+    labels=()
+    while IFS=$'\n' read -r label; do labels+=("$label"); done < <(echo "$content" | jq -r .labels[].name)
+
+    echo -e "--- TITLE\n$title\n--- END\n" > "$old_pr_file_name"
+    echo -e "--- TITLE\n$title\n--- END\n" > "$new_pr_file_name"
+    echo -e "--- EXISTING LABELS" >> "$old_pr_file_name"
+    echo -e "--- EXISTING LABELS" >> "$new_pr_file_name"
+    for label in "${repo_labels[@]}"; do
+        echo "$label" >> "$old_pr_file_name"
+        echo "$label" >> "$new_pr_file_name"
+    done
+    echo -e "--- END\n" >> "$old_pr_file_name"
+    echo -e "--- END\n" >> "$new_pr_file_name"
+
+    echo -e "--- LABELS" >> "$old_pr_file_name"
+    echo -e "--- LABELS" >> "$new_pr_file_name"
+    for label in "${labels[@]}"; do
+        echo "$label" >> "$old_pr_file_name"
+        echo "$label" >> "$new_pr_file_name"
+    done
+    echo -e "--- END\n" >> "$old_pr_file_name"
+    echo -e "--- END\n" >> "$new_pr_file_name"
+
+    echo -e "--- BODY\n" >> "$old_pr_file_name"
+    echo -e "--- BODY\n" >> "$new_pr_file_name"
+    echo "$body" >> "$old_pr_file_name"
+    echo "$body" >> "$new_pr_file_name"
+    echo -e "--- END\n" >> "$old_pr_file_name"
+    echo -e "--- END\n" >> "$new_pr_file_name"
+
+    if [[ $OSTYPE == "darwin"* ]]; then
+        old_file_md5=$(md5 -q "$old_pr_file_name")
+    else
+        old_file_md5=$(md5sum "$old_pr_file_name" | cut -d' ' -f1)
+    fi
+
+    $EDITOR "$new_pr_file_name"
+fi
 
 if [[ $OSTYPE == "darwin"* ]]; then
     new_file_md5=$(md5 -q "$new_pr_file_name")
@@ -109,11 +131,16 @@ done
 
 new_body=$($SED -n '/--- BODY/, /--- END/{ /--- BODY/! { /--- END/! p } }' < "$new_pr_file_name")
 
-gh pr edit \
+if ! output=$(gh pr edit \
     --title "$new_title" \
     --body "$new_body" \
     "${new_labels[@]}" \
-    "${args[@]}" || exit $?
+    "${args[@]}" 2>&1); then
+    >&2 echo
+    error "$output\n"
+    warn "PR file written to $new_pr_file_name"
+    exit 1
+fi
 
 rm -f "$old_pr_file_name"
 rm -f "$new_pr_file_name"
