Adjust logging of custom git scripts

diff --git a/001_zsh/bin/git-clone-bare b/001_zsh/bin/git-clone-bare
--- a/001_zsh/bin/git-clone-bare
+++ b/001_zsh/bin/git-clone-bare
@@ -11,9 +11,16 @@ set -e
 # git-clone-bare-for-worktrees git@github.com:name/repo.git my-repo
 # => Clones to a /my-repo directory
 
+>&2 echo
+
 url=$1
 basename=${url##*/}
 name=${2:-${basename%.*}}
+
+if [[ -d "$name" ]]; then
+    >&2 echo "ERROR: directory '$name' already exists"
+    exit 1
+fi
 
 mkdir "$name"
 cd "$name" || exit
diff --git a/001_zsh/bin/git-repo-name b/001_zsh/bin/git-repo-name
--- a/001_zsh/bin/git-repo-name
+++ b/001_zsh/bin/git-repo-name
@@ -2,6 +2,12 @@
 
 set -e
 
-# Get just the name of the current git repository
-basename -s .git "$(git config --get remote.origin.url)"
+>&2 echo
 
+# Get just the name of the current git repository
+if ! remote=$(git config --get remote.origin.url); then
+    >&2 echo "ERROR: remote repo not found, are you in a git repo?"
+    exit 1
+fi
+
+basename -s .git "$remote"
