Add _git-common and use colours in error/warn logs in git scripts

diff --git a/001_zsh/bin/git-pr-create b/001_zsh/bin/git-pr-create
--- a/001_zsh/bin/git-pr-create
+++ b/001_zsh/bin/git-pr-create
@@ -2,6 +2,10 @@
 
 set -e
 
+CUR_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+
+source "$CUR_DIR/_git-common"
+
 args=()
 pr_types=(python ruby go docker docs documentation)
 pr_type=
@@ -51,7 +55,9 @@ done
 
 # If we have an invalid labels we print an error and exit
 if [[ ${#invalid_labels[@]} -ne 0 ]]; then
-    >&2 printf "\nERROR: the following labels were not found in git repository\n"
+    >&2 echo
+    error "The following labels were not found in git repository"
+    >&2 echo
     >&2 printf "invalid labels -> (%s)\n" "${invalid_labels[*]}"
     exit 1
 fi
diff --git a/001_zsh/bin/gitw-add b/001_zsh/bin/gitw-add
--- a/001_zsh/bin/gitw-add
+++ b/001_zsh/bin/gitw-add
@@ -2,6 +2,10 @@
 
 set -e
 
+CUR_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+
+source "$CUR_DIR/_git-common"
+
 args=()
 branch_name=
 checkout_only=0
@@ -40,7 +44,7 @@ done
 
 if ! is_bare_repo=$(git rev-parse --is-bare-repository 2>&1); then true; fi
 if [[ $is_bare_repo != "true" ]]; then
-    >&2 echo "ERROR: Must be run in a bare repository"
+    error "Must be run in a bare repository!"
     exit 1
 fi
 
@@ -49,7 +53,7 @@ set -- "${args[@]}"
 branch_name="$1"; shift
 
 if [[ -z $branch_name ]]; then
-    >&2 echo "ERROR: must provide a branch name"
+    error "Must provide a branch name"
     exit 1
 fi
 
@@ -77,13 +81,13 @@ if ! output=$(git branch -m "$branch_name" 2>&1); then
     if [[ $output == *"already exists"* ]]; then
         >&2 printf "\nBranch '%s' exists locally, switching to it\n" "$branch_name"
         if ! output=$(git checkout "$branch_name" 2>&1); then
-            >&2 echo "ERROR: Failed to checkout branch : $output"
+            error "Failed to checkout branch : $output"
             exit 1
         fi
         if ! output=$(git rev-parse --abbrev-ref "$branch_name@{upstream}" 2>&1); then
             >&2 echo "Branch '$branch_name' has no upstream set, setting to 'origin/$branch_name'"
             if ! output=$(git branch --set-upstream-to=origin/"$branch_name" 2>&1); then
-                >&2 echo "WARN: Failed to set upstream for branch : $output"
+                warn "Failed to set upstream for branch : $output"
             fi
         fi
     fi
@@ -91,11 +95,11 @@ if ! output=$(git branch -m "$branch_name" 2>&1); then
 elif git branch -r | grep "$branch_name" > /dev/null 2>&1; then
     >&2 printf "\nBranch '%s' exists remotely, setting as upsteam and hard resetting to it\n" "$branch_name"
     if ! output=$(git branch --set-upstream-to=origin/"$branch_name" 2>&1); then
-        >&2 echo "ERROR: Failed to set upstream to branch : $output"
+        error "Failed to set upstream to branch : $output"
         exit 1
     fi
     if ! output=$(git reset --hard origin/"$branch_name" 2>&1); then
-        >&2 echo "ERROR: Failed to hard reset branch : $output"
+        error "Failed to hard reset branch : $output"
         exit 1
     fi
 
@@ -128,4 +132,4 @@ if [[ $checkout_only -ne 1 ]]; then
     fi
 fi
 
->&2 echo "Created worktree '$converted_name'"
+>&2 echo -e "${GREEN_BOLD}Created worktree '$converted_name'${NC}"
