Fix git-clone-bare and gitw-add to set upstream for worktrees

diff --git a/001_zsh/bin/git-clone-bare b/001_zsh/bin/git-clone-bare
--- a/001_zsh/bin/git-clone-bare
+++ b/001_zsh/bin/git-clone-bare
@@ -43,3 +43,14 @@ git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
 # Gets all branches from origin
 git fetch origin
 
+>&2 echo "Creating base worktree"
+if git branch -r | grep origin/master; then
+    base_worktree=master
+elif git branch -r | grep origin/main; then
+    base_worktree=main
+else
+    >&2 echo "ERROR: cannot determine base worktree, main or master don't exist"
+    exit 1
+fi
+
+gitw-add "$base_worktree"
diff --git a/001_zsh/bin/gitw-add b/001_zsh/bin/gitw-add
--- a/001_zsh/bin/gitw-add
+++ b/001_zsh/bin/gitw-add
@@ -5,13 +5,13 @@ set -e
 args=()
 branch_name=
 checkout_only=0
-copy_venv=0
+copy_venv=1
 
 function usage() {
     cat <<-END
 branch_name      name of the branch to create
 --checkout-only  only checkout the branch
---copy           copy .venv from base worktree into new worktree
+--no-copy        don't copy .venv from base worktree into new worktree
 END
 }
 
@@ -25,8 +25,8 @@ while [[ $# -gt 0 ]]; do
         checkout_only=1
         shift
         ;;
-    --copy)
-        copy_venv=1
+    --no-copy)
+        copy_venv=0
         shift
         ;;
     *)
@@ -76,15 +76,23 @@ if ! output=$(git branch -m "$branch_name" 2>&1); then
             >&2 echo "ERROR: Failed to checkout branch : $output"
             exit 1
         fi
-    fi
-else
-    # Check if the branch exists remotely, if it does hard reset to it
-    if git branch -r | grep "$branch_name" > /dev/null 2>&1; then
-        >&2 printf "\nBranch '%s' exists remotely, hard resetting to it\n" "$branch_name"
-        if ! output=$(git reset --hard origin/"$branch_name" 2>&1); then
-            >&2 echo "ERROR: Failed to hard reset branch : $output"
-            exit 1
+        if ! output=$(git rev-parse --abbrev-ref "$branch_name@{upstream}" 2>&1); then
+            >&2 echo "Branch '$branch_name' has no upstream set, setting to origin/$branch_name"
+            if ! output=$(git branch --set-upstream-to=origin/"$branch_name" 2>&1); then
+                >&2 echo "WARN: Failed to set upstream for branch : $output"
+            fi
         fi
+    fi
+# Check if the branch exists remotely, if it does set it as upstream and hard reset to it
+elif git branch -r | grep "$branch_name" > /dev/null 2>&1; then
+    >&2 printf "\nBranch '%s' exists remotely, setting as upsteam and hard resetting to it\n" "$branch_name"
+    if ! output=$(git branch --set-upstream-to=origin/"$branch_name" 2>&1); then
+        >&2 echo "ERROR: Failed to set upstream to branch : $output"
+        exit 1
+    fi
+    if ! output=$(git reset --hard origin/"$branch_name" 2>&1); then
+        >&2 echo "ERROR: Failed to hard reset branch : $output"
+        exit 1
     fi
 fi
 
@@ -92,7 +100,7 @@ fi
 if [[ $checkout_only -ne 1 ]]; then
     base_worktree=$(gitw-get-base)
     if [[ $copy_venv -eq 1 ]] && [[ -d "../$base_worktree/.venv" ]]; then
-        >&2 printf "\nCopying ../%s/.venv to .venv\n" "$base_worktree"
+        >&2 printf "\nCopying ../%s/.venv to %s/.venv\n" "$base_worktree" "$converted_name"
         mkdir -p "$current_dir/$converted_name/.venv"
         # From https://www.zylk.net/en/web-2-0/blog/-/blogs/how-to-copy-files-in-linux-faster-and-safer-than-cp
         cd "$current_dir/$base_worktree/.venv"; tar cf - . | (cd "$current_dir/$converted_name/.venv"; tar xvf -) 2> /dev/null
