Improve error handling in git worktree scripts

diff --git a/001_zsh/bin/gitw-add b/001_zsh/bin/gitw-add
--- a/001_zsh/bin/gitw-add
+++ b/001_zsh/bin/gitw-add
@@ -2,6 +2,14 @@
 
 set -e 
 
+>&2 echo
+
+if ! is_bare_repo=$(git rev-parse --is-bare-repository 2>&1); then true; fi
+if [[ $is_bare_repo != "true" ]]; then
+    >&2 echo "ERROR: Must be run in a bare repository"
+    exit 1
+fi
+
 branch_name="$1"; shift
 
 if [[ -z $branch_name ]]; then
diff --git a/001_zsh/bin/gitw-delete-all b/001_zsh/bin/gitw-delete-all
--- a/001_zsh/bin/gitw-delete-all
+++ b/001_zsh/bin/gitw-delete-all
@@ -2,25 +2,27 @@
 
 set -e
 
+>&2 echo
+
 # Delete all git worktrees in current bare repository
-is_bare_repo=$(git rev-parse --is-bare-repository)
+if ! is_bare_repo=$(git rev-parse --is-bare-repository 2>&1); then true; fi
 if [[ $is_bare_repo != "true" ]]; then
-    echo "Must be run in bare repository"
+    >&2 echo "ERROR: Must be run in a bare repository"
     exit 1
 fi
 
 worktrees=()
 while IFS='' read -r line; do worktrees+=("$line"); done < <(git worktree list | grep -vE "(\[main\]|\[master\]|\(bare\))" | cut -d' ' -f1)
 if [[ ${#worktrees[@]} -eq 0 ]]; then
-    echo "No worktrees to delete"
+    >&2 echo "ERROR: No worktrees to delete"
     exit 1
 fi
 
 for worktree in "${worktrees[@]}"; do
-    printf "\nDeleting worktree : %s\n" "$worktree"
+    >&2 printf "\nDeleting worktree : %s\n" "$worktree"
     if ! result=$(git worktree remove "$worktree" "$@" 2>&1); then
         echo "  $result"
         continue
     fi
-    echo "  Successfully deleted $worktree"
+    >&2 echo "  Successfully deleted $worktree"
 done
diff --git a/001_zsh/bin/gitw-rebase-with-base b/001_zsh/bin/gitw-rebase-with-base
--- a/001_zsh/bin/gitw-rebase-with-base
+++ b/001_zsh/bin/gitw-rebase-with-base
@@ -2,14 +2,15 @@
 
 set -e
 
-in_worktree=$(git rev-parse --is-inside-work-tree)
+>&2 echo
+
+if ! in_worktree=$(git rev-parse --is-inside-work-tree 2>&1); then true; fi
 if [[ $in_worktree == "true" ]]; then
     gitw-update-base
     base_worktree=$(gitw-get-base 2> /dev/null)
     >&2 echo "Rebasing with '$base_worktree' base worktree"
     >&2 git rebase "$base_worktree"
-else
-    echo "ERROR: Must be run inside a git worktree"
-    exit 1
 fi
 
+>&2 echo "ERROR: Must be run inside a git worktree"
+exit 1
diff --git a/001_zsh/bin/gitw-update-base b/001_zsh/bin/gitw-update-base
--- a/001_zsh/bin/gitw-update-base
+++ b/001_zsh/bin/gitw-update-base
@@ -15,24 +15,26 @@ function update_base() {
 
 >&2 echo
 
-is_bare_repo=$(git rev-parse --is-bare-repository)
+if ! is_bare_repo=$(git rev-parse --is-bare-repository 2>&1); then true; fi
 if [[ $is_bare_repo == "true" ]]; then
     update_base
     exit
 fi
 
-in_worktree=$(git rev-parse --is-inside-work-tree)
+if ! in_worktree=$(git rev-parse --is-inside-work-tree 2>&1); then true; fi
 if [[ $in_worktree == "true" ]]; then
     while true; do
         cd ..
+        if ! is_bare_repo=$(git rev-parse --is-bare-repository 2>&1); then true; fi
         is_bare_repo=$(git rev-parse --is-bare-repository)
         if [[ $is_bare_repo == "true" ]]; then
             update_base
             break
         fi
+        # If we made it to the root dir we need to break out here
+        if [[ "$(pwd)" == "/" ]]; then break; fi
     done
-else
-    echo "ERROR: Must be run inside a git worktree or bare repository"
-    exit 1
 fi
 
+>&2 echo "ERROR: Must be run inside a git worktree or bare repository"
+exit 1
