Add gitw-get-base script

diff --git a/001_zsh/bin/gitw-get-base b/001_zsh/bin/gitw-get-base
--- a/001_zsh/bin/gitw-get-base
+++ b/001_zsh/bin/gitw-get-base
@@ -2,22 +2,27 @@
 
 set -e
 
-function update_base() {
-    base_worktree=$(gitw-get-base 2> /dev/null)
+function get_base() {
+    base_worktree=
 
-    >&2 echo "Entering '$base_worktree' base worktree"
-    cd "$base_worktree" || exit
+    if [[ -d main ]]; then
+        base_worktree="main"
+    elif [[ -d master ]]; then
+        base_worktree="master"
+    else
+        >&2 echo "ERROR: main or master worktree not found"
+        return 1
+    fi
 
-    >&2 echo "Updating with remote"
-    # shellcheck disable=SC2210
-    >&2 git pull 
+    >&2 echo -n "Base worktree is: "
+    echo "$base_worktree"
 }
 
 >&2 echo
 
 is_bare_repo=$(git rev-parse --is-bare-repository)
 if [[ $is_bare_repo == "true" ]]; then
-    update_base
+    get_base
     exit
 fi
 
@@ -27,7 +32,7 @@ if [[ $in_worktree == "true" ]]; then
         cd ..
         is_bare_repo=$(git rev-parse --is-bare-repository)
         if [[ $is_bare_repo == "true" ]]; then
-            update_base
+            get_base
             break
         fi
     done
diff --git a/001_zsh/bin/gitw-rebase-with-base b/001_zsh/bin/gitw-rebase-with-base
--- a/001_zsh/bin/gitw-rebase-with-base
+++ b/001_zsh/bin/gitw-rebase-with-base
@@ -4,11 +4,12 @@ set -e
 
 in_worktree=$(git rev-parse --is-inside-work-tree)
 if [[ $in_worktree == "true" ]]; then
-    base_worktree=$(gitw-update-base)
+    gitw-update-base
+    base_worktree=$(gitw-get-base 2> /dev/null)
     >&2 echo "Rebasing with '$base_worktree' base worktree"
-    git rebase "$base_worktree"
+    >&2 git rebase "$base_worktree"
 else
-    echo "Must be run inside a git worktree"
+    echo "ERROR: Must be run inside a git worktree"
     exit 1
 fi
 
