Fix gitw update and rebase with base scripts

diff --git a/001_zsh/bin/gitw-get-base b/001_zsh/bin/gitw-get-base
--- a/001_zsh/bin/gitw-get-base
+++ b/001_zsh/bin/gitw-get-base
@@ -14,17 +14,16 @@ function get_base() {
         return 1
     fi
 
-    >&2 echo -n "Base worktree is: "
     echo "$base_worktree"
 }
-
->&2 echo
 
 if ! is_bare_repo=$(git rev-parse --is-bare-repository 2>&1); then true; fi
 if [[ $is_bare_repo == "true" ]]; then
     get_base
     exit
 fi
+
+got_base=0
 
 if ! in_worktree=$(git rev-parse --is-inside-work-tree 2>&1); then true; fi
 if [[ $in_worktree == "true" ]]; then
@@ -33,6 +32,7 @@ if [[ $in_worktree == "true" ]]; then
         if ! is_bare_repo=$(git rev-parse --is-bare-repository 2>&1); then true; fi
         if [[ $is_bare_repo == "true" ]]; then
             get_base
+            got_base=1
             break
         fi
         # If we made it to the root dir we need to break out here
@@ -40,5 +40,7 @@ if [[ $in_worktree == "true" ]]; then
     done
 fi
 
->&2 echo "ERROR: Must be run inside a git worktree or bare repository"
-exit 1
+if [[ $got_base -ne 1 ]]; then
+    >&2 echo "ERROR: Must be run inside a git worktree or bare repository"
+    exit 1
+fi
diff --git a/001_zsh/bin/gitw-rebase-with-base b/001_zsh/bin/gitw-rebase-with-base
--- a/001_zsh/bin/gitw-rebase-with-base
+++ b/001_zsh/bin/gitw-rebase-with-base
@@ -2,15 +2,15 @@
 
 set -e
 
->&2 echo
-
 if ! in_worktree=$(git rev-parse --is-inside-work-tree 2>&1); then true; fi
 if [[ $in_worktree == "true" ]]; then
     gitw-update-base
-    base_worktree=$(gitw-get-base 2> /dev/null)
+    base_worktree=$(gitw-get-base)
+    >&2 echo
     >&2 echo "Rebasing with '$base_worktree' base worktree"
     >&2 git rebase "$base_worktree"
+else
+    >&2 echo "ERROR: Must be run inside a git worktree"
+    exit 1
 fi
 
->&2 echo "ERROR: Must be run inside a git worktree"
-exit 1
diff --git a/001_zsh/bin/gitw-update-base b/001_zsh/bin/gitw-update-base
--- a/001_zsh/bin/gitw-update-base
+++ b/001_zsh/bin/gitw-update-base
@@ -3,7 +3,7 @@
 set -e
 
 function update_base() {
-    base_worktree=$(gitw-get-base 2> /dev/null)
+    base_worktree=$(gitw-get-base)
 
     >&2 echo "Entering '$base_worktree' base worktree"
     cd "$base_worktree" || exit
@@ -21,6 +21,8 @@ if [[ $is_bare_repo == "true" ]]; then
     exit
 fi
 
+updated_base=0
+
 if ! in_worktree=$(git rev-parse --is-inside-work-tree 2>&1); then true; fi
 if [[ $in_worktree == "true" ]]; then
     while true; do
@@ -29,6 +31,7 @@ if [[ $in_worktree == "true" ]]; then
         is_bare_repo=$(git rev-parse --is-bare-repository)
         if [[ $is_bare_repo == "true" ]]; then
             update_base
+            updated_base=1
             break
         fi
         # If we made it to the root dir we need to break out here
@@ -36,5 +39,7 @@ if [[ $in_worktree == "true" ]]; then
     done
 fi
 
->&2 echo "ERROR: Must be run inside a git worktree or bare repository"
-exit 1
+if [[ $updated_base -ne 1 ]]; then
+    >&2 echo "ERROR: Must be run inside a git worktree or bare repository"
+    exit 1
+fi
