Use env to find bash executable in bash scripts

diff --git a/001_zsh/bin/gitw-add b/001_zsh/bin/gitw-add
--- a/001_zsh/bin/gitw-add
+++ b/001_zsh/bin/gitw-add
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 set -eo pipefail
 
@@ -74,7 +74,7 @@ if ! output=$(git fetch 2>&1); then
     exit 1
 else
     if [[ -n "$output" ]]; then
-        info "$output" 2>&1 | indent
+        echo "$output" | indent
     fi
 fi
 >&2 echo
@@ -86,7 +86,7 @@ if ! output=$(git worktree add "$converted_name" "$@" 2>&1); then
     exit 1
 else
     if [[ -n "$output" ]]; then
-        info "$output" 2>&1 | indent
+        echo "$output" | indent
     fi
 fi
 >&2 echo
@@ -95,39 +95,45 @@ fi
 cd "$converted_name" || exit
 
 info "Creating branch..."
->&2 echo
 
 # Attempt to rename worktree branch to use the correct branch name
 if ! output=$(git branch -m "$branch_name" 2>&1); then
     # If the branch name already exists, check it out instead of creating it
     if [[ $output == *"already exists"* ]]; then
-        info "Branch '$branch_name' exists locally, switching to it" | indent
+        echo "Branch '$branch_name' exists locally, switching to it" | indent
         if ! output=$(git checkout "$branch_name" 2>&1); then
-            error "Failed to checkout branch : $output" | indent
+            error "Failed to checkout branch : $output" 2>&1 | indent
             exit 1
         fi
         if ! output=$(git rev-parse --abbrev-ref "$branch_name@{upstream}" 2>&1); then
-            info "Branch '$branch_name' has no upstream set, setting to 'origin/$branch_name'" | indent
+            echo "Branch '$branch_name' has no upstream set, setting to 'origin/$branch_name'" | indent
             if ! output=$(git branch --set-upstream-to=origin/"$branch_name" 2>&1); then
-                warn "Failed to set upstream for branch : $output" | indent
+                warn "Failed to set upstream for branch : $output" 2>&1 | indent
             fi
         fi
     fi
 # Check if the branch exists remotely, if it does set it as upstream and hard reset to it
 elif git branch -r | grep "$branch_name" > /dev/null 2>&1; then
-    info "Branch '$branch_name' exists remotely, setting as upsteam and hard resetting to it" | indent
+    echo "Branch '$branch_name' exists remotely, setting as upsteam and hard resetting to it" | indent
     if ! output=$(git branch --set-upstream-to=origin/"$branch_name" 2>&1); then
-        error "Failed to set upstream to branch : $output" | indent
+        error "Failed to set upstream to branch : $output" 2>&1 | indent
         exit 1
     fi
     if ! output=$(git reset --hard origin/"$branch_name" 2>&1); then
-        error "Failed to hard reset branch : $output" | indent
+        error "Failed to hard reset branch : $output" 2>&1 | indent
         exit 1
     fi
 
-    info "Running git pull..."
-    git pull
     >&2 echo
+    info "Running git pull..."
+    if ! output=$(git pull 2>&1); then
+        error "$output" 2>&1 | indent
+        exit 1
+    else
+        if [[ -n "$output" ]]; then
+            echo "$output" | indent
+        fi
+    fi
 fi
 
 
@@ -137,19 +143,20 @@ if [[ $checkout_only -ne 1 ]]; then
     base_worktree=$(gitw-get-base 2> /dev/null)
 
     if [[ $copy_venv -eq 1 ]] && [[ -d "../$base_worktree/.venv" ]]; then
-        info "\nCopying ../$base_worktree/.venv to $converted_name/.venv"
+        >&2 echo
+        info "Copying ../$base_worktree/.venv to $converted_name/.venv"
         mkdir -p "$current_dir/$converted_name/.venv"
         # From https://www.zylk.net/en/web-2-0/blog/-/blogs/how-to-copy-files-in-linux-faster-and-safer-than-cp
         cd "$current_dir/$base_worktree/.venv"; tar cf - . | (cd "$current_dir/$converted_name/.venv"; tar xvf -) 2> /dev/null
-        >&2 echo
     elif [[ -f "poetry.lock" ]]; then
+        >&2 echo
         info "Running poetry install..."
         >&2 echo
         script -q /dev/null poetry install
-        >&2 echo
     fi
 
     if [[ -f "pyproject.toml" ]] && [[ -f "$HOME/pyrightconfig.json" ]] && ! [[ -f "pyrightconfig.json" ]]; then
+        >&2 echo
         info "Linking pyrightconfig.json file..."
         >&2 echo 
         ln -s "$HOME/pyrightconfig.json" "pyrightconfig.json"
