Adjust output of gitw-delete-all script to look nicer

diff --git a/001_zsh/bin/gitw-delete-all b/001_zsh/bin/gitw-delete-all
--- a/001_zsh/bin/gitw-delete-all
+++ b/001_zsh/bin/gitw-delete-all
@@ -17,11 +17,12 @@ if [[ $is_bare_repo != "true" ]]; then
         fi
     done < <(find "$(pwd)" -mindepth 1 -maxdepth 1 -type d)
 else
-    info "Checking for git worktrees in $(pwd)"
+    info "Checking for git worktrees in $(pwd)..."
+    >&2 echo
     worktrees=()
     while IFS='' read -r line; do worktrees+=("$line"); done < <(git worktree list | grep -vE "(\[main\]|\[master\]|\(bare\))" | cut -d' ' -f1)
     if [[ ${#worktrees[@]} -eq 0 ]]; then
-        error_no_level "No worktrees to delete" 2>&1 | indent
+        error_no_level "No worktrees to delete" 2>&1
         >&2 echo
         exit 1
     fi
@@ -30,21 +31,21 @@ else
     for worktree in "${worktrees[@]}"; do
         # Check if I have opened a PR for the current branch
         if [[ -d "$worktree" ]] && gh pr list --author "@me" | grep "$(cd "$worktree" && git branch --show-current)" > /dev/null 2>&1; then
-            echo -en "${BLUE_BOLD}$(basename "$worktree")${NC} : " | indent
-            warn_no_level "A PR is open for this worktree, skipping"
+            echo -en "${YELLOW_BOLD}A PR is open for this worktree, skipping${NC} : "
+            echo -e "${BLUE_BOLD}$(basename "$worktree")${NC}"
             >&2 echo
             continue
         fi
         if ! result=$(git worktree remove "$worktree" "$@" 2>&1); then
-            echo -en "${BLUE_BOLD}$(basename "$worktree")${NC} : " | indent
-            error_no_level "Failed to delete"
-            error_no_level "$result" 2>&1 | indent | indent
+            echo -en "${RED_BOLD}Failed to delete${NC} : "
+            echo -e "${BLUE_BOLD}$(basename "$worktree")${NC}"
+            error_no_level "$result" 2>&1
             >&2 echo
             got_error=1
             continue
         fi
-        echo -en "${BLUE_BOLD}$(basename "$worktree")${NC} : " | indent
-        success "Successfully deleted"
+        echo -en "${GREEN_BOLD}Successfully deleted${NC} : "
+        echo -e "${BLUE_BOLD}$(basename "$worktree")${NC}"
         >&2 echo
     done
 
